# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion',
            old_name='cant_bat_usadas',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='fechaAten',
            new_name='atiende',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='hora_inst',
            new_name='cantidad_baterias_usadas',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='kms',
            new_name='comprobante',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='modelo_bat',
            new_name='correo',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='telef_1',
            new_name='descuento',
        ),
        migrations.RenameField(
            model_name='produccion',
            old_name='telef_2',
            new_name='direccion1',
        ),
        migrations.AddField(
            model_name='produccion',
            name='boleta',
            field=models.BooleanField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='produccion',
            name='direccion_atencion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='direccion_rs',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='dni',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='factura',
            field=models.BooleanField(default=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='produccion',
            name='fecha_atencion',
            field=models.DateField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='hora_instalacion',
            field=models.TimeField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='kilometraje',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='misma_direccion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='mismo_cliente',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='modelo_bateria',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='nombre_boleta',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='pago',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='razon_social',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='referencia',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='ruc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='stado',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='telefono_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='telefono_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
