# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180717_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='cliente',
            field=models.CharField(blank=True, help_text='Nombre del Cliente', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 15, 56, 28, 950503), help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='telefono_1',
            field=models.CharField(blank=True, help_text='N\xfamero de tel\xe9fono desde donde llama el cliente', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='telefono_2',
            field=models.CharField(blank=True, help_text='Otro nmero de tel\xe9fono de contacto', max_length=1000, null=True),
        ),
    ]
