# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180717_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='marca_vehiculo',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 16, 18, 5, 470792), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
