# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180717_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='stado',
        ),
        migrations.AddField(
            model_name='produccion',
            name='estado',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 16, 26, 36, 58428), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
