# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-17 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180717_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='cantidad_baterias_usadas',
        ),
        migrations.AlterField(
            model_name='produccion',
            name='cantidad',
            field=models.CharField(blank=True, help_text='Cantidad de baterias usadas', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 17, 18, 20, 43, 444233), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
