# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-24 12:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180717_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='cantidad_bu',
            field=models.CharField(blank=True, help_text='Cantidad de baterias usadas', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='cilindrada',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='gmail',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='produccion',
            name='version',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='cantidad',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 24, 12, 21, 42, 37284), editable=False, help_text='Fecha de recepci\xf3n de la llamada (No se puede modificar)'),
        ),
    ]
